### PR TITLE
added logic for filters in typescript

### PR DESCRIPTION
**Pull request by W-Dominic**
# Allow users to filter data
* For each table or globally, have filters for cutting out unnecessary data
* Example filters: rpm | load | manifold relative pressure | throttle position 

# Implementation
* Used the defineComponent Vue3 which is the newer style of making components in typescript: https://vuejs.org/guide/typescript/overview.html#general-usage-notes
* Implemented reactivity on ```plots``` and ```recievedData``` using both the reactive<> and ref() types:
image
https://vuejs.org/guide/essentials/reactivity-fundamentals.html
* Added a ''watcher' which watches for changes in the ```plots``` variable. If detected, charts are destroyed and reloaded. This is used to detect changes in filters or data. 
image
image
https://vuejs.org/guide/essentials/watchers.html

### CODE REVIEW

**Comment by W-Dominic** [comment]
* Used the defineComponent Vue3 which is the newer style of making components in typescript: https://vuejs.org/guide/typescript/overview.html#general-usage-notes
* Implemented reactivity on plots, and recieved data: 
https://vuejs.org/guide/essentials/reactivity-fundamentals.html
* Added watchers to DataVisualizationPlot so that the charts are reloaded when props change:
https://vuejs.org/guide/essentials/watchers.html

**Comment by W-Dominic** [comment]
As an update I removed the watcher. To reload the child components we only need to increment the key.value at the end of each buildObjects function call.

An open issue exists in prod and on this branch. When switching to a different file and reloading, the data from both files begins to overlap. Feature or bug? Not sure. But im leaning towards bug. The filters work fine even after multiple reloads, and this issue only happens if you switch from one log file to another. 

I will try to fix this. I have an idea

**Comment by W-Dominic** [comment]
I fixed the issue with data overlapping from multiple logs. It ended up being that the ```parsedLogs``` variable wasnt being cleared after each run of buildObjects()

**Comment by W-Dominic** [comment]
# Note about greying out / removing filters for values not in the log file

Another issue. We talked about greying out filters or not showing filters that cannot be used for a specific log file, but I have a couple of issues with this:

## Issues

1) We don't know what filters will be available until we parse the file. We also want to leave filtering an option in this case because big files will crash the browser. 
2) Let's say a filter is greyed out and inaccessible because it was not available for log file A. If the user wants to switch to log file B, they wont be able to use all possible filters because it was blocked from file A. 

## Potential simple solutions

1) Rather than removing / greying out filters that cannot be used for a file, we can simply use an alert() to tell them that the parameter that they want to filter was not found. 
2) Use approach 1 with the alert, but grey our filters that cannot be used. However still allow users to select values for that filter. Essentially just change the color of the filter but dont impact functionality

## More complex solution
* Down the line we want users to be able to save log files, and operate on multiple files during the same session. For example we can store uploaded files in a list, and a user can choose which one they want to see the graphs / analysis for. In that case we can implement filters on a PER FILE basis.  Using this approach, a user can also save their log files with the filters in place, so that when they want to re-open it, they dont need to set filters again. This would require saving the filters, unfiltered data, and filtered data for each file

## My thoughts
For now I think that we should solve this issue in a seperate PR once we add more functionality to the site. Down the line when we want to add support for multiple log files, user saved data, etc. we can revamp the filter system. This way we dont need to implement the same fix twice. 

I was wondering what your thoughts are though. Maybe I am missing a potential idea/solution

**Review by radonc0de — APPROVED** [review]
Couple things:

This looks good for now. It's definitely a significant improvement over what we currently have setup. Transitioning to the new Vue format is also a big step in the right direction. A couple things we should focus on for the next PR:

- Also add filtering for which charts to show. Basically after deciding which charts CAN be displayed, maybe have checkboxes or something similar to actually decide what's displayed. This way, unnecessary charts aren't being displayed and wasting system resources.
- Fixing old log disposal when a new log is uploaded. I read over your ways of doing this and had a couple of ideas myself. Next time we get together for brainstorming, we could combine our solutions and come up with something good. 

But yeah, LGTM

**Pull request merged**
